name: atx-gp
version: 0.0.0
description: Greenpak Gateware for an ATX power supply adapter/FPGA devboard
maintainer: Viktor Kleen <viktor@kleen.org>

defaults:
  local: defaults.yaml

dependencies:
  - base
  - Cabal

  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

library:
  source-dirs: src
  dependencies:
    - clash-topgen
    - kind-generics
    - kind-generics-th
    - mtl
    - singletons <= 2.7
    - template-haskell

  ghc-options:
      - -Wall
      - -Wcompat
      - -haddock
      - -fplugin GHC.TypeLits.Extra.Solver
      - -fplugin GHC.TypeLits.Normalise
      - -fplugin GHC.TypeLits.KnownNat.Solver
      - -fexpose-all-unfoldings
      - -fno-worker-wrapper
      - -Wno-unticked-promoted-constructors

executables:
  shake:
    source-dirs: shake
    main: Main.hs
    when:
      - condition: false
        dependencies: atx-gp
    dependencies:
      - aeson
      - base
      - binary
      - bytestring
      - clash-ghc
      - clash-lib
      - clash-topgen
      - deepseq
      - directory
      - formatting
      - generic-lens
      - hashable
      - lens
      - lens-aeson
      - scientific
      - shake
      - split
      - stache
      - text
      - unordered-containers

tests:
  unit-tests:
    main: unit-tests.hs
    source-dirs: tests
    verbatim:
      type: exitcode-stdio-1.0
    ghc-options:
      - -fplugin GHC.TypeLits.Extra.Solver
      - -fplugin GHC.TypeLits.Normalise
      - -fplugin GHC.TypeLits.KnownNat.Solver
    dependencies:
      - arrows
      - atx-gp
      - clash-prelude
      - generics-sop
      - hedgehog
      - hedgehog-gen
      - sop-core
      - tasty
      - tasty-hedgehog
      - tasty-th
