name: atx-gp
version: 0.0.0
description: Greenpak Gateware for an ATX power supply adapter/FPGA devboard
maintainer: Viktor Kleen <viktor@kleen.org>

defaults:
  local: defaults.yaml

dependencies:
  - base
  - Cabal

  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

library:
  source-dirs: src
  dependencies:
    - template-haskell
    - clash-topgen
    - kind-generics
    - kind-generics-th

  ghc-options:
      - -Wall
      - -Wcompat
      - -haddock
      - -fplugin GHC.TypeLits.Extra.Solver
      - -fplugin GHC.TypeLits.Normalise
      - -fplugin GHC.TypeLits.KnownNat.Solver
      - -fexpose-all-unfoldings
      - -fno-worker-wrapper

executables:
  shake:
    source-dirs: shake
    main: Main.hs
    when:
      - condition: false
        dependencies: atx-gp
    dependencies:
      - base
      - shake
      - clash-topgen
      - clash-ghc
      - clash-shake

tests:
  unit-tests:
    main: unit-tests.hs
    source-dirs: tests
    verbatim:
      type: exitcode-stdio-1.0
    dependencies:
      - atx-gp
      - QuickCheck
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-th
