name: atx-gp
version: 0.0.0
description: Greenpak Gateware for an ATX power supply adapter/FPGA devboard
maintainer: Viktor Kleen <viktor@kleen.org>

defaults:
  local: defaults.yaml

dependencies:
  - base
  - Cabal

  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

library:
  source-dirs: src
  exposed-modules:
    - Example.Project
  dependencies:
    - template-haskell

executables:
  clash:
    main: bin/Clash.hs
    dependencies:
      - base
      - clash-ghc
      - atx-gp
  clashi:
    main: bin/Clashi.hs
    dependencies:
      - base
      - clash-ghc
      - atx-gp

  shake:
    source-dirs: shake
    main: Main.hs
    dependencies:
      - base
      - shake
      - clash-ghc
      - clash-shake

tests:
  unit-tests:
    main: unit-tests.hs
    source-dirs: tests
    verbatim:
      type: exitcode-stdio-1.0
    dependencies:
      - atx-gp
      - QuickCheck
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-th
